language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - cd test
  - chmod +x upload_service_test.py
  - ./upload_service_test.py
  - ./upload_service_test.py --req=POST
  - ./upload_service_test.py --req=POST --files='test'
  - ./upload_service_test.py --req=POST --files='test.jpg'
