"""empty message

Revision ID: 216cacccb2bc
Revises: 
Create Date: 2016-12-07 15:44:03.500090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216cacccb2bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'album', type_='foreignkey')
    op.create_foreign_key(None, 'album', 'user', ['user_id'], ['_id'])
    op.drop_column('album', 'id')
    op.add_column('user', sa.Column('_id', sa.Integer(), nullable=False))
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('user', '_id')
    op.add_column('album', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'album', type_='foreignkey')
    op.create_foreign_key(None, 'album', 'user', ['user_id'], ['id'])
    op.drop_column('album', '_id')
    # ### end Alembic commands ###
